
// <auto-generated />

using System;
using System.Reflection;
using System.Resources;
using System.Globalization;
using System.Threading;

namespace IGeekFan.AspNetCore.Identity.FreeSql
{
    /// <summary>
    ///     This is an internal API that supports the FreeKit infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new FreeKit release.
    /// </summary>
    internal static class CoreStrings
    {
        private static readonly ResourceManager _resourceManager = new ResourceManager("IGeekFan.AspNetCore.Identity.FreeSql.Properties.CoreStrings", typeof(CoreStrings).Assembly);
		
        private static CultureInfo _resourceCulture;
		
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        public static CultureInfo Culture
        {
            get
            {
                return _resourceCulture;
            }
            set
            {
                _resourceCulture = value;
            }
        }

        /// <summary>
        /// 默认情况下，[ProtectedPersonalData]仅适用于字符串。
        /// </summary>
        public static string CanOnlyProtectStrings
            => GetString("CanOnlyProtectStrings");

        /// <summary>
        /// 存在重复邮箱地址
        /// </summary>
        public static string DuplicateEmail
            => GetString("DuplicateEmail");

        /// <summary>
        /// 只能使用从IdentityRole&lt;TKey&gt;派生的角色调用AddFreeSqlStores
        /// </summary>
        public static string NotIdentityRole
            => GetString("NotIdentityRole");

        /// <summary>
        /// AddFreeSqlStores只能由从IdentityUser&lt;TKey&gt;派生的用户调用。
        /// </summary>
        public static string NotIdentityUser
            => GetString("NotIdentityUser");

        /// <summary>
        /// 角色{name} 不存在。
        /// </summary>
        public static string RoleNotFound(object name)
            => string.Format(
                GetString("RoleNotFound", nameof(name)),
                name);

        /// <summary>
        /// 值不能为null或空。
        /// </summary>
        public static string ValueCannotBeNullOrEmpty
            => GetString("ValueCannotBeNullOrEmpty");

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name,_resourceCulture);
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}

